# --- Color Scheme (Everblush) ---
background #141b1e
foreground #b3b9b8
cursor     #b3b9b8

# --- Tab Bar Colors ---
active_tab_background   #232a2d
inactive_tab_background #141b1e
tab_bar_background      #141b1e
active_tab_foreground   #b3b9b8
inactive_tab_foreground #8a9a9e

# Black
color0 #141b1e
color8 #232a2d

# Red
color1 #e57474
color9 #e57474

# Green
color2  #8ccf7e
color10 #8ccf7e

# Yellow
color3  #e5c76b
color11 #e5c76b

# Blue
color4  #67b0e8
color12 #67b0e8

# Magenta
color5  #c47fd5
color13 #c47fd5

# Cyan
color6  #6cbfbf
color14 #6cbfbf

# White
color7  #b3b9b8
color15 #b3b9b8
